########################################
# Stages
#########################################
stages:
  - build

########################################
# Configuration
########################################
variables:
  JOB_BUILD_ENABLED: 'false'
  NODE_BUILD_IMAGE: $NODE_BUILD_IMAGE

########################################
# Jobs
########################################
build:
  stage: build
  image: '$NODE_BUILD_IMAGE'
  cache:
    key:
      files:
        - yarn.lock
      prefix: DEV
    paths:
      - node_modules
    policy: pull
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$JOB_BUILD_ENABLED != "true"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "push" && $CI_PIPELINE_SOURCE != "web"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /chore: Update version/'
      when: never
    - when: on_success
  script:
    - yarn build
